// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:reusable_checklists/data/models/checklist.dart';
import 'package:reusable_checklists/data/models/checklist_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChecklistAdapter());
    registerAdapter(ChecklistItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChecklistAdapter());
    registerAdapter(ChecklistItemAdapter());
  }
}
